### ISSUE TITLE
anh ơi nếu anh là người việt thì anh có thể viết hướng dẫn = tiếng việt ko ạ

### ISSUE THREAD

**Issue by tranvietanh0** [ngpnam261/shub_mcq_assistant#1]
:(((

**Comment by ngpnam261** [comment]
Chào bạn, cảm ơn bạn đã quan tâm, trước hết mình xin làm rõ một số điều như sau:
1. Mình không chịu trách nhiệm nếu script lấy sai đáp án hay bạn bị giáo viên bắt vì sử dụng script. (Use at your own risk)
2. Script này không "hack" đáp án trắc nghiệm trên shub.vn một cách thần kỳ. Cách nó hoạt động là tự động điền đáp án trách nghiệm, check kết quả và sau đó ghi lại đáp án đúng vào key.csv.
3. Bạn KHÔNG NÊN sử dụng tài khoản shub.vn chính. Hãy tạo tải khoản phụ và vào lớp bạn cần lấy đáp án. 
4. Yêu cầu: Mạng hoạt động ổn định.

Nếu bạn vẫn muốn sử dụng thì làm như sau:
1) Cài đặt Google Chrome.
2) Tải ChromeDriver phù hợp với phiên bản Google Chrome bạn đang sử dụng tại [đây](https://chromedriver.chromium.org/downloads).
(nếu bạn đang sử dụng Windows thì tải `chromedriver_win32.zip` rồi giải nén `chromedriver.exe` vào `C:\Windows`)
3) Tải shub_mcq_assistant mới nhất tại [đây](https://github.com/ngpnam261/shub_mcq_assistant/releases) và giải nén tất cả vào một thư mục bất kỳ.
4) Địa chỉ url của bài test trên shub thường như sau `https://shub.edu.vn/class/ABCDE/homework/12345/test` trong đó `ABCDE` là `ClassCode` và `12345` là `TestNumber`.
5) Mở `config.ini` và điền thông tin và lưu lại:
```
[ACCOUNT]
Username = taikhoanphu
Password = 123
[TEST]
ClassCode = ABCDE
TestNumber = 12345
```
Lưu ý: tài khoản phải tham gia vào lớp sẵn trước khi chạy script.
6) Chạy `script.exe`, theo cài đặt mặc định nó sẽ tự động điền và ghi lại đáp án đúng vào `key.csv`. Bạn nên để treo máy cho script tự chạy đến khi lấy đáp án xong để tránh lỗi.

**Comment by Thach2003** [comment]
a ơi NẾU trong trường hợp lớp bị gv closed thì phải thí 1 acc hở a . Nếu execute ngay trên acc chính thì có risk fail k ạ . thx a

**Comment by ngpnam261** [comment]
> a ơi NẾU trong trường hợp lớp bị gv closed thì phải thí 1 acc hở a . Nếu execute ngay trên acc chính thì có risk fail k ạ . thx a
Không có lý do gì xác đáng để chạy script trên acc chính cả. Vì script nó nộp bài để lấy đáp án nên chạy xong thì mất luôn lượt thi rồi.

**Comment by thanchet1487** [comment]
anh ơi mở script.exe như thế nào vậy anh, em mở nó ra trang web script.py

**Comment by ngpnam261** [comment]
> anh ơi mở script.exe như thế nào vậy anh, em mở nó ra trang web script.py

Mình không hiểu ý bạn lắm, sau khi làm các bước như hướng dẫn trên bạn chỉ cần chạy script.exe như các soft bình thường khác thôi?

**Comment by thanchet1487** [comment]
mở = cách doulbe click chuột phải hả anh, hay bằng một phần mềm nào khác nữa ạ, sr em hơi ngu máy tính :<

**Comment by ngpnam261** [comment]
> mở = cách doulbe click chuột phải hả anh, hay bằng một phần mềm nào khác nữa ạ, sr em hơi ngu máy tính :<

Đúng rồi bạn, đọc kỹ lại hướng dẫn ở trên nhé

**Comment by thanchet1487** [comment]
mở cả script với shub lên cùng một lúc hả anh hay có mở cái nào trước hong ạ

**Comment by ngpnam261** [comment]
> mở cả script với shub lên cùng một lúc hả anh hay có mở cái nào trước hong ạ
> 

Em chỉ cần cấu hình script đầy đủ như hướng dẫn trên và mở script thôi, không nên chạy nền gì khác.

**Comment by thanchet1487** [comment]
em đã hoàn thành tất cả các bước, em bấm chạy thì nó hiện cái bảng đen được 1 lúc r biến mất là sao z anh :<

**Comment by ngpnam261** [comment]
> em đã hoàn thành tất cả các bước, em bấm chạy thì nó hiện cái bảng đen được 1 lúc r biến mất là sao z anh :<

Anh vừa mới test lại script và vẫn chạy bình thường, có lẽ mạng em bị lag rồi.
![Screenshot_10](https://user-images.githubusercontent.com/58775514/79464543-63d06080-8024-11ea-978c-d1ee61149d4c.png)
![Screenshot_11](https://user-images.githubusercontent.com/58775514/79464561-68951480-8024-11ea-828d-1b296cc180ab.png)

**Comment by toanlandev02** [comment]
anh ơi file key.csv tự động tạo sau khi mình chạy script.exe à anh

**Comment by toanlandev02** [comment]
![image](https://user-images.githubusercontent.com/53503846/79480565-748ad180-8038-11ea-853e-85c9e330ca07.png)
anh ơi em bị như này là sao vậy ạ

**Comment by ngpnam261** [comment]
> ![image](https://user-images.githubusercontent.com/53503846/79480565-748ad180-8038-11ea-853e-85c9e330ca07.png)
> anh ơi em bị như này là sao vậy ạ

Chắc là do mạng em không load kịp nên script bị lỗi, em thử mở `config.ini` và chỉnh `SleepTime=` lên 1.5 hoặc 2
